on:
  push:
    branches:
      - main

jobs:
  Development:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy to Airflow
        run: sudo cp -r /home/ec2-user dag.py
    env:
      TAG: dev

  QA:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy to Airflow
        run: sudo cp -r /home/ec2-user dag.py
    env:
      TAG: qa
