on:
  push:
    branches:
    - main

jobs:
  QA:
    runs-on: [self-hosted,linux,x64,dev]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy to Airflow
      run: sudo cp -r sample_dag.py /home/ec2-user


  Dev:
    runs-on: [self-hosted,linux,x64,dev]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy to Airflow
      run: sudo cp -r sample_dag.py /home/ec2-user
   

  prod:
    runs-on: [self-hosted,linux,x64,dev]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy to Airflow
      run: sudo cp -r sample_dag.py /home/ec2-user
    
